---
  - name: Install Redis
    apt: name=redis-server
    tags:
      - install

  - name: Change Redis server interface from 127.0.0.1 to 0.0.0.0
    lineinfile:
      dest: /etc/redis/redis.conf
      regexp: '^bind 127.0.0.1'
      line: 'bind 0.0.0.0'
